// lib/games/word_search/word_search_word_bank.dart
// Expanded to 150–200 words per topic covering ALL common valid words.

const Map<String, List<String>> kWordBank = {

  // ─── ANIMALS ────────────────────────────────────────────────
  // Pets, farm, British, American, African, Ocean, Insects, Reptiles, Birds
  'Animals': [
    // 3-letter
    'ANT','APE','ASS','BAT','BEE','COD','COW','EMU','EWE','FOX',
    'GNU','HEN','OWL','PIG','RAM','RAT','YAK','DOG','CAT',
    // 4-letter
    'BEAR','BIRD','BUCK','BULL','CALF','CLAM','COLT','CRAB','CROW',
    'DEER','DOVE','DUCK','FISH','FLEA','FROG','GNAT','GOAT','HARE',
    'HAWK','IBIS','KITE','LAMB','LION','LYNX','MINK','MOLE','MOTH',
    'MULE','NEWT','PONY','PUMA','SEAL','SLUG','SWAN','TOAD','VOLE',
    'WASP','WOLF','WORM','CARP','COLT','DACE','DALE','DOVE','LARK',
    'MYNA','NEWT','PIKE','ROBIN','ROOK','SHAD','TEAL','VOLE','WREN',
    // 5-letter
    'BISON','CIVET','COBRA','CRANE','DINGO','EAGLE','FINCH','GECKO',
    'GOOSE','HIPPO','HORSE','HOUND','HYENA','KOALA','LLAMA','MOOSE',
    'MOUSE','OTTER','PANDA','QUAIL','RAVEN','ROBIN','SHARK','SHEEP',
    'SHREW','SKUNK','SLOTH','SNAKE','SQUID','STORK','TAPIR','TIGER',
    'TROUT','VIXEN','WHALE','ZEBRA','BREAM','CAMEL','CHIMP','CIVET',
    'DINGO','EGRET','GUPPY','HERON','LEECH','LLAMA','MORAY','OKAPI',
    'OTTER','PLOVER','QUOLL','RHINO','SAIGA','STOAT','SWIFT','TAKIN',
    'TAPIR','URIAL','VIPER','WHELK',
    // 6-letter
    'BADGER','BEAVER','CANARY','DONKEY','FALCON','FERRET','GIBBON',
    'IGUANA','JAGUAR','MAGPIE','MONKEY','PARROT','PIGEON','RABBIT',
    'SALMON','TOUCAN','TURKEY','WALRUS','WEASEL','BOBCAT','COUGAR',
    'COYOTE','ERMINE','GANNET','GROUSE','IMPALA','JACKAL','LIZARD',
    'MARMOT','MARTEN','MUSKOX','OSPREY','OYSTER','PARROT','PEAHEN',
    'PLOVER','PUFFIN','PYTHON','RABBIT','RACOON','SHRIMP','THRUSH',
    'TOMCAT','TOUCAN','WOMBAT',
    // 7+ letters
    'BUFFALO','CARIBOU','CHEETAH','CHICKEN','DOLPHIN','GAZELLE',
    'GORILLA','HAMSTER','LOBSTER','MACAQUE','OCTOPUS','OSTRICH',
    'PANTHER','PEACOCK','PELICAN','PENGUIN','PIRANHA','SPARROW',
    'VULTURE','WALLABY','WARTHOG','CHIMPANZEE','FLAMINGO','HEDGEHOG',
    'MEERKAT','MONGOOSE','PLATYPUS','REINDEER','SCORPION','SEAHORSE',
    'SQUIRREL','STARFISH','CHIPMUNK','COCKATOO','CROCODILE','PARAKEET',
    'PORCUPINE','CHAMELEON','ALLIGATOR','ORANGUTAN','SALAMANDER',
  ],

  // ─── SPORT ──────────────────────────────────────────────────
  // British, American, Olympic, Combat, Water, Winter, Individual, Team
  'Sport': [
    // 3–4 letter
    'GOLF','POLO','JUDO','YOGA','SURF','SWIM','DIVE','SAIL','HUNT',
    'LUGE','POLO','SHOT','SPAR','TRAP','TREK',
    // British classics
    'DARTS','RUGBY','CRICKET','NETBALL','SQUASH','SNOOKER','CURLING',
    'CROQUET','HURLING','ROWING','FENCING','ARCHERY','LACROSSE',
    'ROUNDERS','BOWLS','SHINTY','KABADDI',
    // American sports
    'BASEBALL','FOOTBALL','SOFTBALL','BASKETBALL','VOLLEYBALL',
    'WRESTLING','LACROSSE','GRIDIRON',
    // Olympic and global
    'TENNIS','BOXING','SKIING','CYCLING','MARATHON','TRIATHLON',
    'BIATHLON','BADMINTON','HANDBALL','WATERPOLO','EQUESTRIAN',
    'TAEKWONDO','KICKBOXING','KAYAKING','CANOEING','SNOWBOARD',
    'BOBSLEIGH','GYMNASTICS','ATHLETICS','CROSSFIT','PARKOUR',
    'SPRINTING','DECATHLON','PENTATHLON','WEIGHTLIFTING','CLIMBING',
    'TRAMPOLINING','POWERLIFTING','WINDSURFING','MOTORSPORT','SAILING',
    'SHOOTING','SKATING','SKYDIVING','PARAGLIDING','CANOEING',
    'FREEFALL','BOULDERING','CAPOEIRA','SAMBO','SUMO','KENDO',
    'AIKIDO','KARATE','MUAYTHAI','WUSHU','WRESTLING','FENCING',
    'PENTATHLON','HEPTATHLON','STEEPLECHASE','JAVELIN','DISCUS',
    'HAMMER','SHOTPUT','HIGHJUMP','LONGJUMP','POLEVAULT',
    // Fitness and leisure
    'PILATES','SPINNING','AEROBICS','CROSSFIT','ZUMBA','KICKBOXING',
    'MOUNTAINBIKE','TRAILRUN','OPENWATER','FREEDIVE','ICECLIMB',
  ],

  // ─── FOOD ───────────────────────────────────────────────────
  // British comfort, American classics, World cuisine, Ingredients, Desserts
  'Food': [
    // Very short
    'PIE','JAM','HAM','BUN','NAN','OAT','FIG','COD','RYE','TEA',
    'GIN','ALE',
    // British comfort
    'CHIPS','GRAVY','SCONE','PASTY','BACON','TOAST','BREAD','ROAST',
    'STEW','BROTH','CUSTARD','TRIFLE','CRUMPET','HAGGIS','PUDDING',
    'BISCUIT','COLESLAW','SAUSAGE','COBBLER','STILTON','KEDGEREE',
    'KIPPERS','SCAMPI','COCKLES','MARMITE','CHEDDAR','BRANSTON',
    'HOTPOT','STOVIES','CULLEN','TATTIES','BANGERS',
    // American classics
    'BURGER','HOTDOG','MUFFIN','BROWNIE','WAFFLE','GRITS','PRETZEL',
    'PANCAKE','LOBSTER','CORNBREAD','BISCUITS','CLAMBAKE','GUMBO',
    'JAMBALAYA','COLESLAW','CORNDOG','NACHOS','BURRITO','QUESADILLA',
    'PULLED','SMORES','COBBLER','BEIGNET','CRAWFISH','CATFISH',
    // World cuisine
    'PASTA','PIZZA','SUSHI','CURRY','TACOS','CREPE','RISOTTO',
    'HUMMUS','KEBAB','PAELLA','RAMEN','QUICHE','FALAFEL','LASAGNA',
    'TIRAMISU','CROISSANT','DUMPLINGS','ENCHILADA','GOULASH',
    'CEVICHE','TAGINE','SATAY','TEMPURA','COUSCOUS','BIRYANI',
    'FRITTATA','SHAKSHUKA','OMELETTE','SORBET','MOUSSAKA','TZATZIKI',
    'BAKLAVA','PIEROGI','SCHNITZEL','STROGANOFF','RENDANG','PHO',
    'BIBIMBAP','KIMCHI','MISO','SASHIMI','UDON','RAMEN','TEMPEH',
    'INJERA','JOLLOF','BOBOTIE','BUNNY','PERI','SHAWARMA','MEZE',
    // Ingredients and basics
    'STEAK','SALMON','SHRIMP','PRAWN','CHICKEN','BEEF','LAMB','PORK',
    'TOFU','RICE','PASTA','BREAD','EGGS','MILK','CREAM','CHEESE',
    'BUTTER','HONEY','LEMON','MANGO','OLIVE','ONION','GARLIC',
    'GINGER','PEPPER','TOMATO','POTATO','CARROT','BROCCOLI','SPINACH',
    // Desserts
    'CAKE','TART','FLAN','BOMBE','MOUSSE','GANACHE','PRALINE',
    'MADELEINE','PROFITEROLE','ECLAIR','CANELE','DACQUOISE',
  ],

  // ─── HOBBIES ────────────────────────────────────────────────
  // Arts, Sports, Crafts, Digital, Outdoor, Social, Collecting, Music
  'Hobbies': [
    // Very short
    'ART','SEW','RUN','SKI','DIY','GYM','MAP','ROW',
    // Core 20
    'YOGA','COOK','BAKE','READ','DRAW','FISH','KNIT','GAME',
    'HIKE','SWIM','SING','DANCE','CRAFT','WRITE','PAINT','CYCLE',
    'SURF','SAIL','SKATE','CLIMB',
    // Extended single words
    'BOXING','CODING','SEWING','BAKING','HIKING','GAMING','FISHING',
    'KNITTING','POTTERY','ORIGAMI','WEAVING','COOKING','READING',
    'WRITING','PAINTING','DRAWING','DANCING','SINGING','CYCLING',
    'RUNNING','SWIMMING','CLIMBING','SAILING','SURFING','SKATING',
    'SKETCHING','CRAFTING','SCULPTING','BLOGGING','VLOGGING',
    'PODCASTING','STREAMING','WOODWORK','METALWORK','LEATHERWORK',
    'EMBROIDERY','CALLIGRAPHY','BIRDWATCHING','STARGAZING','ASTRONOMY',
    'BEEKEEPING','FORAGING','GARDENING','VOLUNTEERING','COLLECTING',
    'JOURNALING','MEDITATION','PHOTOGRAPHY','FILMMAKING','ANIMATION',
    'DRAWING','SKETCHING','PRINTING','SCREEN','LINOCUT','ETCHING',
    'JUGGLING','MAGIC','COMEDY','IMPROV','ACTING','SINGING','RAPPING',
    'POETRY','STORYTELLING','PUZZLES','CHESS','SCRABBLE','BRIDGE',
    'POKER','DARTS','ARCHERY','SHOOTING','FENCING','BOXING','KARATE',
    'JUDO','YOGA','PILATES','ZUMBA','SPINNING','CROSSFIT','PARKOUR',
    'SKATEBOARDING','SNOWBOARDING','SURFING','WAKEBOARDING','KITESURFING',
    'ROCKCLIMBING','MOUNTAINEERING','CAVING','CANOEING','KAYAKING',
    'SCUBA','SNORKELING','FISHING','HUNTING','CAMPING','HIKING',
    'GEOCACHING','ORIENTEERING','TRAINSPOTTING','PLANESPOTTING',
  ],
};

const Map<String, String> kTopicIcons = {
  'Animals': '🐾',
  'Sport':   '🏆',
  'Food':    '🍽️',
  'Hobbies': '🎨',
};

bool isValidWord(String topic, String word) {
  final bank = kWordBank[topic] ?? [];
  return bank.contains(word.toUpperCase());
}
